### ISSUE TITLE
App cruches and user can not connect to audiochannel anymore

### ISSUE THREAD

**Issue by LauraGroh** [sekassel/STPST21Server#10]
## Is your feature request related to a problem? Please describe.
When the Application crushes (or is stoped by intellij) and the user was connected to an audiochannel the connection stays open.
The server dosn't automaticly dissconnect the user.
But when the User logs in again she is not in any audiomember list but still gets the notification : you are already connected to an audiochannel.
Therfore she can not join an audiochannel.
The messages dose not say whit channel the user is still connected to.
Therfore she has no other option than to logout and wait until she is automaticly logged out after 15 minutes (noop).
(Or to dissconnect from all channels, but that takes a lot of time)

## Describe the solution you'd like
 Discconnect the user automaticly from the connected audiochannel, when the same user loggs in.

## Describe alternatives you've considered
 Send the channel id in the message, that tells us that the user is connected to a channel.

**Comment by KosrenDQ** [comment]
Fixed in Version `4.0.0`
