### ISSUE TITLE
Wrong order of system messages

### ISSUE THREAD

**Issue by LucaHertel** [sekassel/STPST21Server#3]
## Describe the bug
If a user is logging in twice in a row without logging out, the system messages arrive in the following order:

1. user X joined
2. user X joined
3. user X left

## To Reproduce
Send the login request for user X twice without a logout request.

## Expected behavior
Recieve the system messages in the following order:

1. user X joined
2. user X left
3. user X joined

## Screenshots
N.A.

## Additional context
N.A.

**Comment by KosrenDQ** [comment]
Do any other Teams have this issue, too?
I can not reproduce the error with my client.

**Comment by LucaHertel** [comment]
Just added our messages.
![SystemMessages](https://user-images.githubusercontent.com/74049400/117576343-ef140c80-b0e5-11eb-8f5b-0d5f6259fef3.png)

**Comment by KosrenDQ** [comment]
Will be fixed in Version `2.0.0`
