### ISSUE TITLE
Hashed Passwords

### ISSUE THREAD

**Issue by EricRode** [sekassel/STPST21Server#4]
## Is your feature request related to a problem? Please describe.

We have a new feature for automated login. To implement that we need to save the username and the password locally.
The problem is that our password is sent (and saved) currently in plain text, which is very insecure.

## Describe the solution you'd like

We would like to have a separate URL for login and registration with a hashed password. So that we could log in to the hashed URL and if some other teams don't want to support it they could log in to the normal login URL. The normal login should then internally hash the password so that a user can log in on both types of Clients.

## Describe alternatives you've considered

- You could force everybody to hash their password e.g. with sha256.
- Both variants could be saved on the server and the server checks if the incoming password is a normal or a hashed one.

**Comment by DrunkBlood** [comment]
Can't you hash the password on login and send the hash encoded Base64 to the server. I only see one flaw in my proposal such that if I log in from a diffrent client and they process the password differently then we have a collision. But that should not be a problem since in the end we should only have one client which gets accepted, right? For password hashing I would recommend bcrypt or scrypt although PBKDF2 is already implemented in java 11 without a library.

**Comment by KosrenDQ** [comment]
Why should this increase security? We use SSL which means username and password are encrypted. 
You can hash the username/password locally and de-hash it and send it to the server, or an even better idea is that your client encrypt this username and password with some strong algorithm like AES or RSA and saves the encrypted string on disk. Later, only the specific client which creates the encrypted string can decrypt it, so you can perform the automated login. 
Is this possible for you or do I miss a point?

**Comment by EricRode** [comment]
Thank you for the fast answer. We decided to encrypt it on our own as you suggested. The main reason why we wanted the feature was that we did not know how you test our client. Because if you register a user on another Client and try to login into ours that would not work. We thought that this would be a problem. But when you say that this is okay then we will do it like that. Thanks.
