### ISSUE TITLE
Keine Websocket Nachricht beim verlassen eines privilegierten Channels

### ISSUE THREAD

**Issue by JulianWerner98** [sekassel/STPST21Server#6]
Ablauf/Verhalten:
Zwei User sind Mitglied eines privilegierten Channels. 
Der erste User updated nun den Channel und entfernt Person 2 aus der Memberliste.
Somit ist Person nicht länger Mitglied des Channels.
Allerdings wird Person 2 im laufenden Betrieb nicht darüber informiert, dass sie nicht mehr Teil der Member ist.
Somit wählt sie dann den Channel und bekommt beim Message senden einen Error.

Andere User werden allerdings über das update informiert!

Erwartetes Verhalten:
Der User der entfernt wurde bekommt eine channelDelete Message

**Comment by KosrenDQ** [comment]
Mit Version `3.0.1` behoben
