### ISSUE TITLE
Servers of Temp Users

### ISSUE THREAD

**Issue by SoerenMoeller** [sekassel/STPST21Server#7]
## Describe the bug
The request to get information about the server returns no body (null), if a (most likely deleted) temporary user is the owner.
I guess there is a problem in returning information, when the owner of the server got deleted

## To Reproduce
1. Create a temporary account
2. Invite a 'normal' account 
3. Join the server with the normal account
4. Wait until the temporary user gets deleted
5. The 'normal' user get's no information about the server back, seems like he can't leave the server either

## Expected behavior
The server gets deleted or the body returns the expected information

**Comment by KosrenDQ** [comment]
Fixed in version `3.0.2`
