### ISSUE TITLE
Logging out doesn't send message that user disconnected from audio channel

### ISSUE THREAD

**Issue by DanielErhard** [sekassel/STPST21Server#8]
## Describe the bug
When you connected to an audio channel and then logged out of the account, the server does not send a system message that you left the audio channel automatically.

## To Reproduce
1. Open the application in two accounts that are on the same server. One account is only to see the server system messages.
2. Connect to an audio channel with one account.
3. Log out with this account, without sending the message that you disconnect from the audio channel.
4. The other account will not receive a message that you disconnected from the audio channel. (The message that you went offline will be received however)

## Expected behavior
When a user loggs out, the system message that he disconnected from any audio channels that he was connected with, is sent.

**Comment by KosrenDQ** [comment]
Fixed in version `3.0.2`
