### ISSUE TITLE
Api: Upgrade channel to priviledged causes priviledged members to receive channelDeleted message

### ISSUE THREAD

**Issue by Tillio** [sekassel/STPST21Server#9]
## Describe the bug
When upgrading a unpriviledged text channel to priviledged (including all server members) the user receives a "action:channelDeleted" message over the /system Websocket.

## To Reproduce
1. Create a server and invite a least one user
2. send a request to upgrade the default channel to priviledged. 
   Include the id's of all server members in the request

3. receive an action: channelDeleted message via the /system Websocket

## Expected behavior
all server members should only receive the action:channelUpdated message and not the action: channelDeleted message

## Additional context
the request seems to work the intended way when not all members are included

**Comment by KosrenDQ** [comment]
Fixed in version `3.0.2`
